apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n0khce0fr-nodejs 
  janus-idp.io/tekton: n0khce0fr-nodejs
  backstage.io/kubernetes-id: n0khce0fr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n0khce0fr-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  